# Generated by Django 5.2 on 2025-05-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
