# Generated by Django 5.2 on 2025-04-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('marketing', 'Marketing'), ('business', 'Business'), ('data', 'Data Science'), ('language', 'Language'), ('personal_dev', 'Personal Development')], default='programming', max_length=100),
        ),
    ]
