# Generated by Django 5.2 on 2025-04-21 00:11

import courses.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=courses.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
