# Generated by Django 5.2 on 2025-04-21 00:26

import courses.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=courses.storage_backends.PublicThumbnailStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=courses.storage_backends.PublicProfilePicStorage(), upload_to=''),
        ),
    ]
